import React from 'react'
import {twMerge as cs} from 'tailwind-merge'
// @ts-ignore
import * as icons from 'feather-icons-react'

export type IconProps = Omit<React.HtmlHTMLAttributes<SVGElement>, 'color'> & {
  name: IconName
  size?: string | number
  fill?: string
  filled?: boolean
  color?: string | null
}

export function Icon(props: IconProps) {
  let {className, name, fill, filled, color, size, ...rest} = props
  const IconComponent = icons[name]

  if (!IconComponent) {
    throw new Error(`${name} is not a valid icon name`)
  }

  return (
    <IconComponent
      {...rest}
      icon={name}
      className={cs(
        'Icon',
        color === undefined && 'text-slate-800 dark:text-slate-200',
        'max-w-max w-[1em] h-[1em]',
        className,
      )}
      fill={fill || (filled && 'currentColor')}
      style={{color, fontSize: size}}
    />
  )
}

export type IconName =
  | 'Activity'
  | 'Airplay'
  | 'AlertCircle'
  | 'AlertOctagon'
  | 'AlertTriangle'
  | 'AlignCenter'
  | 'AlignJustify'
  | 'AlignLeft'
  | 'AlignRight'
  | 'Anchor'
  | 'Aperture'
  | 'Archive'
  | 'ArrowDownCircle'
  | 'ArrowDownLeft'
  | 'ArrowDownRight'
  | 'ArrowDown'
  | 'ArrowLeftCircle'
  | 'ArrowLeft'
  | 'ArrowRightCircle'
  | 'ArrowRight'
  | 'ArrowUpCircle'
  | 'ArrowUpLeft'
  | 'ArrowUpRight'
  | 'ArrowUp'
  | 'AtSign'
  | 'Award'
  | 'BarChart_2'
  | 'BarChart'
  | 'BatteryCharging'
  | 'Battery'
  | 'BellOff'
  | 'Bell'
  | 'Bluetooth'
  | 'Bold'
  | 'BookOpen'
  | 'Book'
  | 'Bookmark'
  | 'Box'
  | 'Briefcase'
  | 'Calendar'
  | 'CameraOff'
  | 'Camera'
  | 'Cast'
  | 'CheckCircle'
  | 'CheckSquare'
  | 'Check'
  | 'ChevronDown'
  | 'ChevronLeft'
  | 'ChevronRight'
  | 'ChevronUp'
  | 'ChevronsDown'
  | 'ChevronsLeft'
  | 'ChevronsRight'
  | 'ChevronsUp'
  | 'Chrome'
  | 'Circle'
  | 'Clipboard'
  | 'Clock'
  | 'CloudDrizzle'
  | 'CloudLightning'
  | 'CloudOff'
  | 'CloudRain'
  | 'CloudSnow'
  | 'Cloud'
  | 'Code'
  | 'Codepen'
  | 'Codesandbox'
  | 'Coffee'
  | 'Columns'
  | 'Command'
  | 'Compass'
  | 'Copy'
  | 'CornerDownLeft'
  | 'CornerDownRight'
  | 'CornerLeftDown'
  | 'CornerLeftUp'
  | 'CornerRightDown'
  | 'CornerRightUp'
  | 'CornerUpLeft'
  | 'CornerUpRight'
  | 'Cpu'
  | 'CreditCard'
  | 'Crop'
  | 'Crosshair'
  | 'Database'
  | 'Delete'
  | 'Disc'
  | 'DivideCircle'
  | 'DivideSquare'
  | 'Divide'
  | 'DollarSign'
  | 'DownloadCloud'
  | 'Download'
  | 'Dribbble'
  | 'Droplet'
  | 'Edit_2'
  | 'Edit_3'
  | 'Edit'
  | 'ExternalLink'
  | 'EyeOff'
  | 'Eye'
  | 'Facebook'
  | 'FastForward'
  | 'Feather'
  | 'Figma'
  | 'FileMinus'
  | 'FilePlus'
  | 'FileText'
  | 'File'
  | 'Film'
  | 'Filter'
  | 'Flag'
  | 'FolderMinus'
  | 'FolderPlus'
  | 'Folder'
  | 'Framer'
  | 'Frown'
  | 'Gift'
  | 'GitBranch'
  | 'GitCommit'
  | 'GitMerge'
  | 'GitPullRequest'
  | 'Github'
  | 'Gitlab'
  | 'Globe'
  | 'Grid'
  | 'HardDrive'
  | 'Hash'
  | 'Headphones'
  | 'Heart'
  | 'HelpCircle'
  | 'Hexagon'
  | 'Home'
  | 'Image'
  | 'Inbox'
  | 'Info'
  | 'Instagram'
  | 'Italic'
  | 'Key'
  | 'Layers'
  | 'Layout'
  | 'LifeBuoy'
  | 'Link_2'
  | 'Link'
  | 'Linkedin'
  | 'List'
  | 'Loader'
  | 'Lock'
  | 'LogIn'
  | 'LogOut'
  | 'Mail'
  | 'MapPin'
  | 'Map'
  | 'Maximize_2'
  | 'Maximize'
  | 'Meh'
  | 'Menu'
  | 'MessageCircle'
  | 'MessageSquare'
  | 'MicOff'
  | 'Mic'
  | 'Minimize_2'
  | 'Minimize'
  | 'MinusCircle'
  | 'MinusSquare'
  | 'Minus'
  | 'Monitor'
  | 'Moon'
  | 'MoreHorizontal'
  | 'MoreVertical'
  | 'MousePointer'
  | 'Move'
  | 'Music'
  | 'Navigation_2'
  | 'Navigation'
  | 'Octagon'
  | 'Package'
  | 'Paperclip'
  | 'PauseCircle'
  | 'Pause'
  | 'PenTool'
  | 'Percent'
  | 'PhoneCall'
  | 'PhoneForwarded'
  | 'PhoneIncoming'
  | 'PhoneMissed'
  | 'PhoneOff'
  | 'PhoneOutgoing'
  | 'Phone'
  | 'PieChart'
  | 'PlayCircle'
  | 'Play'
  | 'PlusCircle'
  | 'PlusSquare'
  | 'Plus'
  | 'Pocket'
  | 'Power'
  | 'Printer'
  | 'Radio'
  | 'RefreshCcw'
  | 'RefreshCw'
  | 'Repeat'
  | 'Rewind'
  | 'RotateCcw'
  | 'RotateCw'
  | 'Rss'
  | 'Save'
  | 'Scissors'
  | 'Search'
  | 'Send'
  | 'Server'
  | 'Settings'
  | 'Share_2'
  | 'Share'
  | 'ShieldOff'
  | 'Shield'
  | 'ShoppingBag'
  | 'ShoppingCart'
  | 'Shuffle'
  | 'Sidebar'
  | 'SkipBack'
  | 'SkipForward'
  | 'Slack'
  | 'Slash'
  | 'Sliders'
  | 'Smartphone'
  | 'Smile'
  | 'Speaker'
  | 'Square'
  | 'Star'
  | 'StopCircle'
  | 'Sun'
  | 'Sunrise'
  | 'Sunset'
  | 'Tablet'
  | 'Tag'
  | 'Target'
  | 'Terminal'
  | 'Thermometer'
  | 'ThumbsDown'
  | 'ThumbsUp'
  | 'ToggleLeft'
  | 'ToggleRight'
  | 'Tool'
  | 'Trash_2'
  | 'Trash'
  | 'Trello'
  | 'TrendingDown'
  | 'TrendingUp'
  | 'Triangle'
  | 'Truck'
  | 'Tv'
  | 'Twitch'
  | 'Twitter'
  | 'Type'
  | 'Umbrella'
  | 'Underline'
  | 'Unlock'
  | 'UploadCloud'
  | 'Upload'
  | 'UserCheck'
  | 'UserMinus'
  | 'UserPlus'
  | 'UserX'
  | 'User'
  | 'Users'
  | 'VideoOff'
  | 'Video'
  | 'Voicemail'
  | 'Volume_1'
  | 'Volume_2'
  | 'VolumeX'
  | 'Volume'
  | 'Watch'
  | 'WifiOff'
  | 'Wifi'
  | 'Wind'
  | 'XCircle'
  | 'XOctagon'
  | 'XSquare'
  | 'X'
  | 'Youtube'
  | 'ZapOff'
  | 'Zap'
  | 'ZoomIn'
  | 'ZoomOut'
