import React from 'react'
import {ComponentStory, ComponentMeta} from '@storybook/react'

import {Icon, type IconProps} from './icon'

// More on default export: https://storybook.js.org/docs/react/writing-stories/introduction#default-export
export default {
  title: 'Components/Icon',
  component: Icon,
  // More on argTypes: https://storybook.js.org/docs/react/api/argtypes
  argTypes: {},
} as ComponentMeta<typeof Icon>

const Template: ComponentStory<typeof Icon> = (args) => (
  <div className="p-16">
    <Icon {...args} />
  </div>
)

export const Default = Template.bind({})
Default.args = {
  name: 'Heart',
}

export const XLarge = Template.bind({})
XLarge.args = {
  size: 72,
  name: 'Heart',
}

export const OtherColor = Template.bind({})
OtherColor.args = {
  name: 'Heart',
  color: 'red',
}

export const Filled = Template.bind({})
Filled.args = {
  name: 'Heart',
  color: 'limegreen',
  filled: true,
}

export const FilledWithOtherColor = Template.bind({})
FilledWithOtherColor.args = {
  name: 'Heart',
  fill: 'red',
}

// More on component templates: https://storybook.js.org/docs/react/writing-stories/introduction#using-args
export const AllIcons: ComponentStory<typeof Icon> = (args) => {
  let tdThClassName = 'border border-black p-2 text-left dark:border-white dark:text-white'

  return (
    <table className="border-collapse ">
      <thead>
        <tr>
          <th className={tdThClassName}>Icon</th>
          <th className={tdThClassName}>Code</th>
        </tr>
      </thead>
      <tbody>
        {allIconNames.map((iconName) => (
          <tr key={iconName}>
            <td className={tdThClassName}>
              <Icon {...args} name={iconName} />
            </td>
            <td className={tdThClassName}>
              <code>{`<Icon name="${iconName}" />`}</code>
            </td>
          </tr>
        ))}
      </tbody>
    </table>
  )
}

// More on args: https://storybook.js.org/docs/react/writing-stories/args
AllIcons.args = {
  size: 48,
}

let allIconNames: Array<IconProps['name']> = [
  'Activity',
  'Airplay',
  'AlertCircle',
  'AlertOctagon',
  'AlertTriangle',
  'AlignCenter',
  'AlignJustify',
  'AlignLeft',
  'AlignRight',
  'Anchor',
  'Aperture',
  'Archive',
  'ArrowDownCircle',
  'ArrowDownLeft',
  'ArrowDownRight',
  'ArrowDown',
  'ArrowLeftCircle',
  'ArrowLeft',
  'ArrowRightCircle',
  'ArrowRight',
  'ArrowUpCircle',
  'ArrowUpLeft',
  'ArrowUpRight',
  'ArrowUp',
  'AtSign',
  'Award',
  'BarChart_2',
  'BarChart',
  'BatteryCharging',
  'Battery',
  'BellOff',
  'Bell',
  'Bluetooth',
  'Bold',
  'BookOpen',
  'Book',
  'Bookmark',
  'Box',
  'Briefcase',
  'Calendar',
  'CameraOff',
  'Camera',
  'Cast',
  'CheckCircle',
  'CheckSquare',
  'Check',
  'ChevronDown',
  'ChevronLeft',
  'ChevronRight',
  'ChevronUp',
  'ChevronsDown',
  'ChevronsLeft',
  'ChevronsRight',
  'ChevronsUp',
  'Chrome',
  'Circle',
  'Clipboard',
  'Clock',
  'CloudDrizzle',
  'CloudLightning',
  'CloudOff',
  'CloudRain',
  'CloudSnow',
  'Cloud',
  'Code',
  'Codepen',
  'Codesandbox',
  'Coffee',
  'Columns',
  'Command',
  'Compass',
  'Copy',
  'CornerDownLeft',
  'CornerDownRight',
  'CornerLeftDown',
  'CornerLeftUp',
  'CornerRightDown',
  'CornerRightUp',
  'CornerUpLeft',
  'CornerUpRight',
  'Cpu',
  'CreditCard',
  'Crop',
  'Crosshair',
  'Database',
  'Delete',
  'Disc',
  'DivideCircle',
  'DivideSquare',
  'Divide',
  'DollarSign',
  'DownloadCloud',
  'Download',
  'Dribbble',
  'Droplet',
  'Edit_2',
  'Edit_3',
  'Edit',
  'ExternalLink',
  'EyeOff',
  'Eye',
  'Facebook',
  'FastForward',
  'Feather',
  'Figma',
  'FileMinus',
  'FilePlus',
  'FileText',
  'File',
  'Film',
  'Filter',
  'Flag',
  'FolderMinus',
  'FolderPlus',
  'Folder',
  'Framer',
  'Frown',
  'Gift',
  'GitBranch',
  'GitCommit',
  'GitMerge',
  'GitPullRequest',
  'Github',
  'Gitlab',
  'Globe',
  'Grid',
  'HardDrive',
  'Hash',
  'Headphones',
  'Heart',
  'HelpCircle',
  'Hexagon',
  'Home',
  'Image',
  'Inbox',
  'Info',
  'Instagram',
  'Italic',
  'Key',
  'Layers',
  'Layout',
  'LifeBuoy',
  'Link_2',
  'Link',
  'Linkedin',
  'List',
  'Loader',
  'Lock',
  'LogIn',
  'LogOut',
  'Mail',
  'MapPin',
  'Map',
  'Maximize_2',
  'Maximize',
  'Meh',
  'Menu',
  'MessageCircle',
  'MessageSquare',
  'MicOff',
  'Mic',
  'Minimize_2',
  'Minimize',
  'MinusCircle',
  'MinusSquare',
  'Minus',
  'Monitor',
  'Moon',
  'MoreHorizontal',
  'MoreVertical',
  'MousePointer',
  'Move',
  'Music',
  'Navigation_2',
  'Navigation',
  'Octagon',
  'Package',
  'Paperclip',
  'PauseCircle',
  'Pause',
  'PenTool',
  'Percent',
  'PhoneCall',
  'PhoneForwarded',
  'PhoneIncoming',
  'PhoneMissed',
  'PhoneOff',
  'PhoneOutgoing',
  'Phone',
  'PieChart',
  'PlayCircle',
  'Play',
  'PlusCircle',
  'PlusSquare',
  'Plus',
  'Pocket',
  'Power',
  'Printer',
  'Radio',
  'RefreshCcw',
  'RefreshCw',
  'Repeat',
  'Rewind',
  'RotateCcw',
  'RotateCw',
  'Rss',
  'Save',
  'Scissors',
  'Search',
  'Send',
  'Server',
  'Settings',
  'Share_2',
  'Share',
  'ShieldOff',
  'Shield',
  'ShoppingBag',
  'ShoppingCart',
  'Shuffle',
  'Sidebar',
  'SkipBack',
  'SkipForward',
  'Slack',
  'Slash',
  'Sliders',
  'Smartphone',
  'Smile',
  'Speaker',
  'Square',
  'Star',
  'StopCircle',
  'Sun',
  'Sunrise',
  'Sunset',
  'Tablet',
  'Tag',
  'Target',
  'Terminal',
  'Thermometer',
  'ThumbsDown',
  'ThumbsUp',
  'ToggleLeft',
  'ToggleRight',
  'Tool',
  'Trash_2',
  'Trash',
  'Trello',
  'TrendingDown',
  'TrendingUp',
  'Triangle',
  'Truck',
  'Tv',
  'Twitch',
  'Twitter',
  'Type',
  'Umbrella',
  'Underline',
  'Unlock',
  'UploadCloud',
  'Upload',
  'UserCheck',
  'UserMinus',
  'UserPlus',
  'UserX',
  'User',
  'Users',
  'VideoOff',
  'Video',
  'Voicemail',
  'Volume_1',
  'Volume_2',
  'VolumeX',
  'Volume',
  'Watch',
  'WifiOff',
  'Wifi',
  'Wind',
  'XCircle',
  'XOctagon',
  'XSquare',
  'X',
  'Youtube',
  'ZapOff',
  'Zap',
  'ZoomIn',
  'ZoomOut',
]
